language: objective-c
osx_image: xcode8.3
env:
  - PLATFORM=Mac
  - PLATFORM=iOS NAME='iPhone SE'
  - PLATFORM=tvOS NAME='Apple TV 1080p'
before_install:
  - if [ -n "$NAME" ]; then
      export UUID=$(instruments -s | ruby -e "ARGF.each_line{ |ln| ln =~ /$NAME .* \[(.*)\]/; if \$1; puts(\$1); exit; end }");
    fi
install:
  - carthage bootstrap --platform $PLATFORM
script:
  - set -o pipefail;
    case $PLATFORM in
    Mac)
      xcodebuild -scheme PMKQuartzCore test | xcpretty;;
    iOS|tvOS)
      open -a "simulator" --args -CurrentDeviceUDID "$UUID";
      xcodebuild -scheme PMKQuartzCore -destination "id=$UUID" test | xcpretty;;
    esac
